openapi: 3.0.2
info:
  title: Ecommerce
  description: "Prueba técnica"
  termsOfService: http://swagger.io/terms/
  contact:
    email: valdez.jose.francisco@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1-SNAPSHOT
servers:
  - url:
tags:
  - name: price
    description: Operations about prices
paths:
  /price:
    get:
      tags:
        - price
      parameters:
        - name: date
          in: query
          description: Application date for example 2023-07-24T22:30:30.307Z
          required: true
          schema:
            type: string
            format: date-time
        - name: product_id
          in: query
          description: Product identification for example 35455
          required: true
          schema:
            type: integer
            format: int32
        - name: brand_id
          in: query
          description: Brand identification for example 1=Zara
          required: true
          schema:
            type: integer
            format: int32
      summary: Get price
      operationId: getLastPrice
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDTO'
        400:
          description: Invalid input
        404:
          description: Price not found
components:
  schemas:
    PriceDTO:
      type: object
      properties:
        product_id:
          type: integer
          format: int32
        brand_id:
          type: integer
          format: int32
        price_list:
          type: integer
          format: int32
        start_date:
          type: string
          format: date-time
        end_date:
          type: string
          format: date-time
        final_price:
          type: number
          format: double